// src/editor/Editor.vue
<script setup lang="ts">
import { env } from '#config/env-client';
import { LexicalComposer } from 'lexical-vue/LexicalComposer';
import { ContentEditable } from 'lexical-vue/LexicalContentEditable';
import { ListPlugin } from 'lexical-vue/LexicalListPlugin';
import { RichTextPlugin } from 'lexical-vue/LexicalRichTextPlugin';
import CollaborationPlugin from './plugins/collaboration/CollaborationPlugin.vue';
import { IndentationPlugin } from './plugins/IndentationPlugin';
import { RootSchemaPlugin } from './plugins/RootSchemaPlugin';
import { SchemaValidationPlugin } from './plugins/SchemaValidationPlugin';
import { TreeViewPlugin } from './plugins/TreeViewPlugin';
import { useEditorConfig } from './config';
import './Editor.css';

const { initialConfig } = useEditorConfig();
const isDev = env.isDev;
</script>

<template>
  <div class="editor-container">
    <LexicalComposer :initial-config="initialConfig">
      <RichTextPlugin>
        <template #contentEditable>
          <ContentEditable class="editor-input">
            <template #placeholder>
              <div class="editor-placeholder">
                Start typing your outline…
              </div>
            </template>
          </ContentEditable>
        </template>
      </RichTextPlugin>
      <IndentationPlugin />
      <ListPlugin :has-strict-indent="true" />
      <CollaborationPlugin>
        <RootSchemaPlugin />
        <slot />
      </CollaborationPlugin>
      <SchemaValidationPlugin v-if="isDev" />
      <TreeViewPlugin v-if="isDev" />
    </LexicalComposer>
  </div>
</template>

// src/editor/Editor.tsx
import { LexicalComposer } from '@lexical/react/LexicalComposer';
import { ContentEditable } from '@lexical/react/LexicalContentEditable';
import { LexicalErrorBoundary } from '@lexical/react/LexicalErrorBoundary';
import { ListPlugin } from '@lexical/react/LexicalListPlugin';
import { RichTextPlugin } from '@lexical/react/LexicalRichTextPlugin';
import { config } from '#config/client';
import { createEditorInitialConfig } from '../../lib/editor/config';
import { CollaborationPlugin } from './plugins/collaboration';
import { IndentationPlugin } from './plugins/IndentationPlugin';
import { DevPlugin } from './plugins/DevPlugin';
import { RootSchemaPlugin } from './plugins/RootSchemaPlugin';
import './Editor.css';

interface EditorProps {
  children?: React.ReactNode;
}

export default function Editor({ children }: EditorProps) {
  const editorInitialConfig = createEditorInitialConfig({ isDev: config.isDev });
  return (
    <div className="editor-container">
      <LexicalComposer initialConfig={editorInitialConfig}>
        <RichTextPlugin
          contentEditable={<ContentEditable className="editor-input" />}
          ErrorBoundary={LexicalErrorBoundary}
        />
        <IndentationPlugin />
        <ListPlugin hasStrictIndent />
        <CollaborationPlugin>
          <RootSchemaPlugin />
          <DevPlugin>{children}</DevPlugin>
        </CollaborationPlugin>
      </LexicalComposer>
    </div>
  );
}
