// src/editor/plugins/dev/SchemaValidationPlugin.tsx
import { useLexicalComposerContext } from '@lexical/react/LexicalComposerContext';
import { useEffect } from 'react';
import { useCollaborationStatus } from '../collaboration';
import { assertEditorSchema } from './schema/assertEditorSchema';

export function SchemaValidationPlugin(): null {
  const [editor] = useLexicalComposerContext();
  const { hydrated, docEpoch } = useCollaborationStatus();

  useEffect(() => {
    if (!hydrated) {
      return;
    }

    return editor.registerUpdateListener(() => {
      try {
        const state = editor.getEditorState().toJSON();
        assertEditorSchema(state);
      } catch (error) {
        console.error('[RemDo] Editor schema validation failed.', error);
      }
    });
  }, [editor, hydrated, docEpoch]);

  return null;
}

export default SchemaValidationPlugin;

// src/editor/plugins/SchemaValidationPlugin.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted } from 'vue';
import { useLexicalComposer } from 'lexical-vue/LexicalComposer';
import { assertEditorSchema } from '@/editor/schema/assertEditorSchema';

const editor = useLexicalComposer();

let unregister: (() => void) | undefined;

onMounted(() => {
  unregister = editor.registerUpdateListener(() => {
    try {
      const state = editor.getEditorState().toJSON();
      assertEditorSchema(state);
    } catch (error) {
      console.error('[RemDo] Editor schema validation failed.', error);
    }
  });
});

onBeforeUnmount(() => {
  unregister?.();
});
</script>

<template>
  <slot />
</template>
