// src/editor/plugins/collaboration/CollaborationProvider.tsx
import type { ReactNode } from 'react';
import { env } from '#config/env.client';
import { createContext, use, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { ProviderFactory } from './collaborationRuntime';
import { CollaborationSyncController, createProviderFactory } from './collaborationRuntime';

interface CollaborationStatusValue {
  ready: boolean;
  enabled: boolean;
  providerFactory: ProviderFactory;
  hasUnsyncedChanges: boolean;
  waitForSync: () => Promise<void>;
}

const missingContextError = new Error('Collaboration context is missing. Wrap the editor in <CollaborationProvider>.');

const CollaborationStatusContext = createContext<CollaborationStatusValue | null>(null);

// eslint-disable-next-line react-refresh/only-export-components -- Safe: hook reads context without holding component state.
export function useCollaborationStatus(): CollaborationStatusValue {
  const value = use(CollaborationStatusContext);

  if (!value) {
    throw missingContextError;
  }

  return value;
}

export function CollaborationProvider({ children }: { children: ReactNode }) {
  const value = useCollaborationRuntimeValue();

  return <CollaborationStatusContext value={value}>{children}</CollaborationStatusContext>;
}

function useCollaborationRuntimeValue(): CollaborationStatusValue {
  const enabled = env.collabEnabled;
  const [ready, setReady] = useState(!enabled);
  const [unsynced, setUnsynced] = useState(enabled);
  const endpoint = useMemo(() => {
    const { protocol, hostname } = window.location;
    const wsProtocol = protocol === 'https:' ? 'wss' : 'ws';
    return `${wsProtocol}://${hostname}:${env.collabPort}`;
  }, []);

  const syncController = useMemo(
    () => new CollaborationSyncController(setUnsynced, enabled),
    [enabled, setUnsynced]
  );
  const waitersRef = useRef<Set<() => void>>(new Set());

  const flushWaiters = useCallback(() => {
    if (waitersRef.current.size === 0) {
      return;
    }

    const waiters = Array.from(waitersRef.current);
    waitersRef.current.clear();
    for (const resolve of waiters) {
      resolve();
    }
  }, []);

  useEffect(() => {
    if (!enabled) {
      syncController.setUnsynced(false);
    }
  }, [enabled, syncController]);

  const providerFactory = useMemo(
    () => createProviderFactory({ setReady, syncController }, endpoint),
    [endpoint, setReady, syncController]
  );

  const resolvedReady = !enabled || ready;
  const hasUnsyncedChanges = enabled && unsynced;

  useEffect(() => {
    if (!enabled || (resolvedReady && !hasUnsyncedChanges)) {
      flushWaiters();
    }
  }, [enabled, flushWaiters, hasUnsyncedChanges, resolvedReady]);

  const waitForSync = useCallback(() => {
    if (!enabled || (resolvedReady && !hasUnsyncedChanges)) {
      return Promise.resolve();
    }

    return new Promise<void>((resolve) => {
      const waiters = waitersRef.current;
      const release = () => {
        waiters.delete(release);
        resolve();
      };

      waiters.add(release);

      if (!enabled || (resolvedReady && !hasUnsyncedChanges)) {
        release();
      }
    });
  }, [enabled, hasUnsyncedChanges, resolvedReady]);

  return useMemo<CollaborationStatusValue>(
    () => ({
      ready: resolvedReady,
      enabled,
      providerFactory,
      hasUnsyncedChanges,
      waitForSync,
    }),
    [enabled, hasUnsyncedChanges, providerFactory, resolvedReady, waitForSync]
  );
}

export type { CollaborationStatusValue };

// src/editor/plugins/collaboration/CollaborationProvider.vue
<script setup lang="ts">
import { provide } from 'vue';
import { env } from '#config/env-client';
import { CollaborationSyncController, createProviderFactory } from './collaborationRuntime';
import { collaborationStatusKey } from './status';
import type { CollaborationStatusValue } from './status';
import type { ProviderFactory } from './collaborationRuntime';

class CollaborationStatus implements CollaborationStatusValue {
  private readyInternal: boolean;
  private unsyncedInternal: boolean;
  private providerFactoryInternal: ProviderFactory = () => {
    throw new Error('Collaboration provider not initialized');
  };
  private readonly waiters = new Set<() => void>();
  private readonly readyListeners = new Set<(ready: boolean) => void>();

  constructor(private readonly enabledInternal: boolean) {
    this.readyInternal = !enabledInternal;
    this.unsyncedInternal = enabledInternal;
  }

  get ready(): boolean {
    return !this.enabledInternal || this.readyInternal;
  }

  get enabled(): boolean {
    return this.enabledInternal;
  }

  get providerFactory(): ProviderFactory {
    return this.providerFactoryInternal;
  }

  get hasUnsyncedChanges(): boolean {
    return this.enabledInternal && this.unsyncedInternal;
  }

  waitForSync(): Promise<void> {
    if (!this.enabledInternal || (this.readyInternal && !this.unsyncedInternal)) {
      return Promise.resolve();
    }

    return new Promise<void>((resolve) => {
      const release = () => {
        this.waiters.delete(release);
        resolve();
      };

      this.waiters.add(release);

      if (!this.enabledInternal || (this.readyInternal && !this.unsyncedInternal)) {
        release();
      }
    });
  }

  onReadyChange(listener: (ready: boolean) => void): () => void {
    this.readyListeners.add(listener);
    listener(this.ready);
    return () => {
      this.readyListeners.delete(listener);
    };
  }

  setProviderFactory(factory: ProviderFactory): void {
    this.providerFactoryInternal = factory;
  }

  setUnsynced(value: boolean): void {
    if (this.unsyncedInternal === value) {
      return;
    }

    this.unsyncedInternal = value;
    this.flushWaiters();
  }

  setReady(value: boolean): void {
    if (this.readyInternal === value) {
      return;
    }

    this.readyInternal = value;
    this.readyListeners.forEach((listener) => {
      listener(this.ready);
    });
    this.flushWaiters();
  }

  private flushWaiters() {
    if (!this.enabledInternal || (this.readyInternal && !this.unsyncedInternal)) {
      if (this.waiters.size === 0) {
        return;
      }

      const pending = Array.from(this.waiters);
      this.waiters.clear();
      for (const release of pending) {
        release();
      }
    }
  }
}

const enabled = env.collabEnabled;
const status = new CollaborationStatus(enabled);

const syncController = new CollaborationSyncController((value) => {
  status.setUnsynced(value);
}, enabled);

const endpoint = (() => {
  if (typeof window === 'undefined') {
    return '';
  }

  const { protocol, hostname } = window.location;
  const wsProtocol = protocol === 'https:' ? 'wss' : 'ws';
  return `${wsProtocol}://${hostname}:${env.collabPort}`;
})();

const providerFactory = createProviderFactory(
  {
    setReady: (value: boolean) => {
      status.setReady(value);
    },
    syncController,
  },
  endpoint,
);

status.setProviderFactory(providerFactory);

provide(collaborationStatusKey, status);
</script>

<template>
  <slot />
</template>
